#!/bin/bash

# rollbar deploy notification
# $1: status (started, succeeded, failed, timed_out) https://docs.rollbar.com/reference#post-deploy
rollbar_notify() {
	if [ -n "$ROLLBAR_ACCESS_TOKEN" ]; then
		echo "ROLLBAR_ACCESS_TOKEN found. Will report to Rollbar."
		curl -vs --request POST \
			--url https://api.rollbar.com/api/1/deploy/ \
			--header 'content-type: application/json' \
			--data "{\"access_token\":\"$ROLLBAR_ACCESS_TOKEN\",\
				\"environment\":\"$ROLLBAR_ENVIRONMENT\",\
				\"revision\":\"$SOURCE_COMMIT\",\
				\"local_username\":\"dockerhub\",\
				\"status\":\"${1-succeeded}\"}"
	fi
}

# install google cloud sdk, instructions from https://cloud.google.com/sdk/docs/downloads-apt-get

export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt-get update && apt-get install -y google-cloud-sdk

# deploy master branch to dev, tags to prod
if [ "$SOURCE_BRANCH" = "master" ]; then
	GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY_PROD"
	GCLOUD_PROJECT_ID="$GCLOUD_PROJECT_ID_PROD"
	ROLLBAR_ENVIRONMENT="production"
else
	GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY_DEV"
	GCLOUD_PROJECT_ID="$GCLOUD_PROJECT_ID_DEV"
	ROLLBAR_ENVIRONMENT="development"
fi

# get the image name
# $DOCKER_REPO is something like index.docker.io/tridnguyen/forms
# split by / and get the last element
REPO_NAME=$(echo "$DOCKER_REPO" | awk -F'/' '{print $NF}')

printenv

rollbar_notify 'started'

echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
gcloud config set project $GCLOUD_PROJECT_ID
gcloud --quiet auth configure-docker
export GCLOUD_IMAGE_TAG="us.gcr.io/$GCLOUD_PROJECT_ID/$REPO_NAME:$DOCKER_TAG"
docker tag $IMAGE_NAME $GCLOUD_IMAGE_TAG
docker push $GCLOUD_IMAGE_TAG

gcloud config set run/region us-central1
gcloud beta run deploy $REPO_NAME --image $GCLOUD_IMAGE_TAG --platform managed

local deploy_status=$?
if [ $deploy_status -ne 0 ]; then
	rollbar_notify 'failed'
else
	rollbar_notify
fi
